### ISSUE TITLE
Katanas and Rapiers use the same recipes

### ISSUE THREAD

**Issue by Derpford** [Draylar/gate-of-babylon#11]
This isn't so much of an issue when playing alongside Polymorph (which allows choosing the output when recipes conflict), but the Rapier and the Katana have the same recipe. Given that the Extended Stick is only used in the Spear right now, what I'd do is make the Katana use the Extended Stick in place of the regular stick (since katanas are traditionally two-handed weapons anyway). You could also move the stick one slot to the right on the Katana and add a third piece of the material (which would match up with the Katana's higher damage output compared to vanilla swords of the same material).

**Comment by ShabanPlayz** [comment]
or make the katana crafting recipe mirrored

**Comment by Draylar** [comment]
I'm rolling with the idea of having Katanas require the extended stick in the next update (and removing Polymorph as a JIJ from Gate of Babylon). Thanks for the suggestions!
