### ISSUE TITLE
Spears should have more/vanilla enchantments (sharpness, knockback, etc.)

### ISSUE THREAD

**Issue by Gremious** [Draylar/gate-of-babylon#28]
Spears are really dope
But the fact that you can put a lot of enchantments on a bladed weapon, whilst spears appear to only allow for unbreaking (?) makes them not as fun and not as viable both
They should accept sharpness, knockback, elemental aspects, and perhaps even loyalty

If differenciation from tridents is important, consider mechanics like giving them a small sweep used only for knockback, or less damage but allow for (cross)bow enchantments (e.g quick charge)

I assume this is planned as this mod is beta, but I'll open this issues for tracking

**Comment by Draylar** [comment]
Fully fixed in the next update. Have fun with your Fire Aspect, Lightning-channeling spears! 🔥⚡
