### ISSUE TITLE
suggestion: make that you can't use the katana special attack while sneaking.

### ISSUE THREAD

**Issue by xelotex** [Draylar/gate-of-babylon#29]
(read the tittle) that way you can sneak and use the shield without trigger the katana special attack.

**Comment by muevoid** [comment]
Yes this would be very nice same for the rapier imo. Or possibly be able to bind the special to another key would be my preferred way?

**Comment by xelotex** [comment]
i think both solutions are good, they should implement both, maybe they should add my solution first and then make your solution an configurable option, something like "special_attacks_require_a_keybind_to_excecute:true". I prefer this because sometimes when you have a big modpack installed you ran out of keybinds, that's why i prefer that the especial attacks gets blocked when sneaking, that way you don't waste keybinds, but i know that some people would prefer a keybind to trigger the especial attack, that's why it's better to implement both solutions.

**Comment by J3LL4** [comment]
Actually, I thought not being able too use offhand was katana's downside, to make up for it's crazy high damage

**Comment by muevoid** [comment]
Pretty sure katana damage got nerfed for next update.
