### ISSUE TITLE
The Katana and Rapier have the same crafting recipe

### ISSUE THREAD

**Issue by John24314** [Draylar/gate-of-babylon#35]
i took screenshots of both the rapier and katana page, and both are the same recipe, making one, in my survival playthrough, the katana uncraftable.
![img comp 1](https://user-images.githubusercontent.com/75639963/110180228-3caa8b00-7dbe-11eb-9b60-7791107155ad.JPG)
![img comp 2](https://user-images.githubusercontent.com/75639963/110180231-3d432180-7dbe-11eb-98b2-76482d19e75f.JPG)

**Comment by Draylar** [comment]
GOB bundles Polymorph for recipe conflicts in <1.3.0, so it is still craftable. In the latest version (>1.3.0), the katana recipe has been mirrored, and Polymorph has been removed. The wiki needs to be updated to reflect that.

**Comment by John24314** [comment]
thanks
