### ISSUE TITLE
Boomerangs never lose durability

### ISSUE THREAD

**Issue by saltyseadoggo** [Draylar/gate-of-babylon#47]
Boomerangs never lose durability when they hit a mob or when they are used as a melee weapon, despite having durability values. Testable by obtaining any boomerang in a new world, spawning mobs such as husks, entering survival mode, and throwing it at them or meleeing them. One would expect them to suffer a durability cost per hit, like other weapons, so they eventually need to be replaced, as being unbreakable increases their favourability over other weapons by a fair bit in survival mode.

**Comment by Draylar** [comment]
Fixed, thanks!
