### ISSUE TITLE
Weapons right clock doing self damage?

### ISSUE THREAD

**Issue by InfernalGoon69** [Draylar/gate-of-babylon#57]
Katana and Waraxe right clicks seem to be doing full damage to your person. If this is a feature then the 2 weapons are kinda useless lol. Thought i saw an issue about it here earlier today. so far loving the other weapons tho for sure. Going to start a pvp arena on my server soon would love to include all the weapons for the battle arena.

**Comment by Draylar** [comment]
Was fixed in [1.4.4](https://github.com/Draylar/gate-of-babylon/releases/tag/1.4.4-1.16.5), let me know if you have any other issues :)
