### ISSUE TITLE
Katanas are currently Uncraftable. [1.17]

### ISSUE THREAD

**Issue by Coffe-e** [Draylar/gate-of-babylon#62]
I was wondering how I would craft a Katana, so I had checked the wiki. After seeing that it shared a recipe for the Rapier, I checked the previously closed issues.

I saw that in #35 , you said that the recipe had been mirrored, but currently mirroring the recipe still makes a rapier. I'm not sure if I'm missing something, but for now i believe that the katana is uncraftable.

![2021-06-17_23 27 12](https://user-images.githubusercontent.com/65330012/122516464-a93f4380-cfc3-11eb-9e9e-b2b3cbd5bca4.png)

Changing the katana or rapier to have one diamond to the right/left of the stick could fix this issue, and I believe that the rapier makes the most sense in having it, since rapiers usually have guards around their handle.

**Comment by SladeWOOMY** [comment]
i created this account just for this:
 
 put to sticks together diagonally.

ur welcome!

**Comment by miracleman64** [comment]
yeah bruh
you need extended stick
