### ISSUE TITLE
more boomerang functions should be added

### ISSUE THREAD

**Issue by miracleman64** [Draylar/gate-of-babylon#65]
boomerangs should be able to pick up items, activate levers and be shot through dispensers. i think this would be a neat feature to include, and if this dosent get added, honestly i don't care. thanks anyway!

**Comment by Draylar** [comment]
Just implemented Boomerangs flipping buttons & levers, as well as Dispenser-shot Boomerangs in the latest update. Thank you for the great suggestions!
