### ISSUE TITLE
[Enhancement] Add A Boomerang-style Weapon

### ISSUE THREAD

**Issue by Lv44EnderShaman** [Draylar/gate-of-babylon#7]
I was thinking that maybe adding some form of ranged melee weapon to compliment the Trident and Spears would be a good idea. Maybe something like a Boomerang, or a Yo-Yo a-la Terraria, or even, say, a Wrench inspired by Ratchet & Clank's Omniwrench. Figured I'd float the idea and see if it was a good contribution.

**Comment by Draylar** [comment]
[Boomerangs ](https://streamable.com/fw30ik)and Yo-Yos are being added in the next update; thank you for the suggestion! 🥳
