### ISSUE TITLE
Compatibility with LevelZ (Modpack reference is Medieval Modpack by Sharkie TV)

### ISSUE THREAD

**Issue by BlitzenZizi** [Draylar/gate-of-babylon#70]
### I just wanna preface this that I really don't know how this mod is the mod listed as causing the crash ### 

Regardless of that though others do seem to enjoy it so I would like to at least see if a compatibility patch or something could be added. I again don't really know if the issue stems from this mod or LevelZ, but I know that the crash lists THIS mod and not LevelZ as being the cause of the crash. The crash log will be available below, just as a reference point. Personally I prefer this mod of LevelZ but I cannot be 100% that LevelZ is even apart of it. I am assuming it is as its the only mod that affects what happens when a mob is attacked, and its only when you attack a mob with the spears, swords, or rapiers. Some of the weapons don't appear to have this issue while others do. This crash log is listed below:
[crash-2021-09-02_17.33.15-client.txt](https://github.com/Draylar/gate-of-babylon/files/7111867/crash-2021-09-02_17.33.15-client.txt)

If you have any questions about what I was doing when it crashed, I was attacking a fish with a stone spear. My boyfriend also attacked a Zombie and the game crashed also.

**Comment by Draylar** [comment]
Seems like LevelZ [casts tools you use to MiningToolItem](https://github.com/Globox1997/LevelZ/blob/c307e4a7abeffceb0b43c9ef7b2d0781809fe89f/src/main/java/net/levelz/mixin/player/PlayerEntityMixin.java#L134) if they directly inherit from `ToolItem`. I would recommend opening an issue on [their repository](https://github.com/Globox1997/LevelZ) with a link to this issue, and then Globox & I can figure out a solution to fix it. Thanks for the report!
