### ISSUE TITLE
Weapon balance

### ISSUE THREAD

**Issue by Thaumatarge** [Draylar/gate-of-babylon#9]
A lot of weapons have mismatched tiering with gold and wood, where they are supposed to practically be identical in damage and attack speed, but not harvest speed and durability. Katanas are too powerful in high tiers, and the secondary ability would easily make up for lower damage. The lunge on Rapiers allows for easy flight.

I believe that katanas should be in the same range as a sword, dealing a little bit less damage but being faster. Lunging on rapiers should be severely diminished while in mid air if not completely impossible. Gold and Wood should be in the same tier.

Also, what is the purpose of the Haladies, and why does my character hold it by the blade?

**Comment by Draylar** [comment]
I fixed your mentioned issues in the next update:
 - Most tools now have the same/similar stats for gold and wood, aside from durability
 - Nerfed Katana damage & ability damage, slightly increased attack speed
 - Rapiers can now only lunge once before the player lands on the ground (no flying, but can be used off a jump)

Haladies were supposed to have a double-hit gimmick, but I can't get it to work, so they kind of "just exist," for now.

**Comment by flier268** [comment]
Katana does not increase attack speed on 1680af0083f13dc5095c159647f2cc79f93ee72d

**Comment by Draylar** [comment]
was in a5b469944ce833de0020029856961934d65538d7, bad commit names
